DerivingParser subclass: #Empty
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Parsing-Derivatives'!
!Empty commentStamp: 'fbs 8/30/2012 16:09' prior: 0!
I represent the empty parser.!




!Empty methodsFor: 'parsing' stamp: 'fbs 8/30/2012 18:17'!
or: aParser
	^ aParser.! !

!Empty methodsFor: 'parsing' stamp: 'fbs 8/30/2012 18:03'!
then: aParser
	^ self.! !


